#######################################################################
# Wiki.js - CONFIGURATION DEFAULT                                     #
#######################################################################

# ---------------------------------------------------------------------
# Title of this site
# ---------------------------------------------------------------------

title="Wiki"

# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host="http://35.242.133.113"


